// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
// (This first version is a hand-written seed: the '7' roster's own alignment
// with a man-leaning scheme — exactly makeGenome(DEFENSE_SPEC).)
export const DEFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "note": "hand-written seed: roster alignment, man-leaning scheme"
  },
  "values": {
    "pos:d-nt:across": 0, "pos:d-nt:down": 1,
    "pos:d-dt1:across": -2.5, "pos:d-dt1:down": 1,
    "pos:d-dt2:across": 2.5, "pos:d-dt2:down": 1,
    "pos:d-cb1:across": -15, "pos:d-cb1:down": 2,
    "pos:d-cb2:across": 15, "pos:d-cb2:down": 2,
    "pos:d-lb:across": 0, "pos:d-lb:down": 4,
    "pos:d-s:across": 0, "pos:d-s:down": 8,
    "zone:d-cb1:across": -12, "zone:d-cb1:depth": 4,
    "zone:d-cb2:across": 12, "zone:d-cb2:depth": 4,
    "zone:d-lb:across": 0, "zone:d-lb:depth": 3,
    "zone:d-s:across": 0, "zone:d-s:depth": 9,
    "cov:dist": 1, "cov:depth": 0, "cov:width": 0,
    "scheme:bias": -2, "scheme:down": 0, "scheme:toGo": 0, "scheme:spread": 0
  }
};
