// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
export const DEFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "trainedBy": "tools/train-defense.js",
    "opponent": "scripted autoplanOffense",
    "options": {
      "generations": 25,
      "popSize": 14,
      "plays": 20,
      "seed": 1,
      "sigma": 0.08
    },
    "fitness": 5.464329987304101
  },
  "values": {
    "pos:d-nt:across": -7.933389504318805,
    "pos:d-nt:down": 2.157889388751516,
    "pos:d-dt1:across": 0.6941207257351502,
    "pos:d-dt1:down": 0.8509485720884664,
    "pos:d-dt2:across": 9.233977357552238,
    "pos:d-dt2:down": 0.5,
    "pos:d-cb1:across": -7.8434511316824915,
    "pos:d-cb1:down": 2.0747692411612437,
    "pos:d-cb2:across": 17.01855765543579,
    "pos:d-cb2:down": 3.852489887287786,
    "pos:d-lb:across": -5.417225403865329,
    "pos:d-lb:down": 1.5067006085757422,
    "pos:d-s:across": -10.113341692898514,
    "pos:d-s:down": 3.8999868097340564,
    "zone:d-cb1:across": 3.1964764110289208,
    "zone:d-cb1:depth": 3.7889252615756455,
    "zone:d-cb2:across": -1.9547747747609536,
    "zone:d-cb2:depth": 5.088549501945944,
    "zone:d-lb:across": 15.427660417790307,
    "zone:d-lb:depth": 2.7910590888101527,
    "zone:d-s:across": 2.94810582469566,
    "zone:d-s:depth": 6.490856758276694,
    "cov:dist": 0.4593779170621058,
    "cov:depth": -0.7880892904284243,
    "cov:width": -0.2377586166182829,
    "scheme:bias": 0.16044391754516257,
    "scheme:down": 0.374989316229165,
    "scheme:toGo": -0.17154225589119937,
    "scheme:spread": 1.305630117957835
  }
};
