// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
export const DEFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "trainedBy": "tools/train-coevolve.js",
    "opponent": "co-evolved learned offense",
    "options": {
      "generations": 15,
      "popSize": 10,
      "plays": 12,
      "elite": 3,
      "sigma": 0.06,
      "hof": 2,
      "seed": 1
    },
    "fitness": -0.669666259003879
  },
  "values": {
    "pos:d-nt:across": -4.648282040359561,
    "pos:d-nt:down": 6.16533081800488,
    "pos:d-dt1:across": 3.677351643906653,
    "pos:d-dt1:down": 2.6075703258810443,
    "pos:d-dt2:across": 10.562580199477754,
    "pos:d-dt2:down": 4.621759692778237,
    "pos:d-cb1:across": -7.614753436426813,
    "pos:d-cb1:down": 1.6630727644539314,
    "pos:d-cb2:across": 18.022737552862232,
    "pos:d-cb2:down": 5.436475526041451,
    "pos:d-lb:across": 2.4165727833682817,
    "pos:d-lb:down": 1.3860375928530004,
    "pos:d-s:across": -18.473135978830218,
    "pos:d-s:down": 6.898542229282166,
    "zone:d-cb1:across": -2.3912595415737394,
    "zone:d-cb1:depth": 1.161650362524286,
    "zone:d-cb2:across": -0.5271825087841169,
    "zone:d-cb2:depth": 4.901722335126099,
    "zone:d-lb:across": 16.813315211013773,
    "zone:d-lb:depth": 3.8348302329524673,
    "zone:d-s:across": 6.526425416659014,
    "zone:d-s:depth": 3.481995450372206,
    "cov:dist": 0.13761300656963604,
    "cov:depth": -0.7151660032493741,
    "cov:width": 0.28847168463852674,
    "scheme:bias": 2.4621235593881203,
    "scheme:down": -3.2879121602060386,
    "scheme:toGo": 1.6645967225552951,
    "scheme:spread": 1.9662413586016099
  }
};
