// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
export const OFFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "trainedBy": "tools/train-coevolve.js",
    "opponent": "co-evolved learned defense",
    "options": {
      "generations": 15,
      "popSize": 10,
      "plays": 12,
      "elite": 3,
      "sigma": 0.06,
      "hof": 2,
      "seed": 1
    },
    "fitness": 40.23806781646024
  },
  "values": {
    "pos:o-c:across": -6.463661739545612,
    "pos:o-c:down": -1.1332839084342163,
    "pos:o-lg:across": -0.17862191604881006,
    "pos:o-lg:down": -0.5980486070333131,
    "pos:o-rg:across": 2.015929937340304,
    "pos:o-rg:down": -1.0089821402251569,
    "pos:o-wr1:across": -6.488936475126197,
    "pos:o-wr1:down": -0.7667421904641828,
    "pos:o-wr2:across": 16.24346719384864,
    "pos:o-wr2:down": -1.251357158201384,
    "pos:o-qb:across": -3.7032230259294305,
    "pos:o-qb:down": -4.597452153040528,
    "pos:o-rb:across": -1.3029950813203155,
    "pos:o-rb:down": -6.847161972040685,
    "call:bias": -2.03063306670795,
    "call:down": 1.4376995081521262,
    "call:toGo": 2.110313320623931,
    "call:box": 3.457255950947876,
    "run:sideBias": -0.13335558666276048,
    "run:read": 6.83866963455535,
    "run:lean": 0.6759973112443434,
    "throw:go": -17.56668119593663,
    "throw:hold": 2.889214613265748,
    "qb:drop": 0.6631522928760477,
    "tgt:sep": 0.6679170786690535,
    "tgt:depth": 0.6126602349230359,
    "tgt:dist": -0.7068137296714952,
    "route:o-wr1:deg0": -47.03039005320868,
    "route:o-wr1:degLate": -40.672775623532274,
    "route:o-wr2:deg0": 14.745647258880698,
    "route:o-wr2:degLate": -37.74104772138037,
    "route:o-rb:deg0": 42.52291201268631,
    "route:o-rb:degLate": 46.14259909325804
  }
};
