// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
export const OFFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "trainedBy": "tools/train-coevolve.js",
    "opponent": "co-evolved learned defense",
    "options": {
      "generations": 25,
      "popSize": 12,
      "plays": 16,
      "elite": 3,
      "sigma": 0.06,
      "hof": 2,
      "seed": 1
    },
    "fitness": 27.8433493977327
  },
  "values": {
    "pos:o-c:across": -4.682506917542076,
    "pos:o-c:down": -1.3079999210601425,
    "pos:o-lg:across": -15.585517548915817,
    "pos:o-lg:down": -1.228094813180761,
    "pos:o-rg:across": -7.333867548854134,
    "pos:o-rg:down": -1.0199559301195504,
    "pos:o-wr1:across": -11.797660317612209,
    "pos:o-wr1:down": -0.570460702263512,
    "pos:o-wr2:across": 23.590070255909776,
    "pos:o-wr2:down": -1.0206123073768185,
    "pos:o-qb:across": 24,
    "pos:o-qb:down": -2.759340418375944,
    "pos:o-rb:across": 19.286167573189267,
    "pos:o-rb:down": -6.231953511878418,
    "call:bias": -0.6080132002785972,
    "call:down": 2.962374239633171,
    "call:toGo": 2.0232179417169527,
    "call:box": 1.404352314226079,
    "run:sideBias": -1.0146131652744745,
    "run:read": 6.539086009442746,
    "run:lean": 0.7759110950959883,
    "throw:go": -13.032566898476722,
    "throw:hold": 3.7744140317982096,
    "qb:drop": 0.4258773373568086,
    "tgt:sep": 0,
    "tgt:depth": 2,
    "tgt:dist": -0.8529751719258308,
    "route:o-wr1:deg0": -56.69857796735997,
    "route:o-wr1:degLate": -39.00299228598399,
    "route:o-wr2:deg0": 0.19780361407874913,
    "route:o-wr2:degLate": -29.32456566283895,
    "route:o-rb:deg0": 79.05681390518164,
    "route:o-rb:degLate": 67.11179291054877
  }
};
