// GENERATED by the training tools in tools/ — retrain rather than editing by hand.
// (This first version is a hand-written seed: the '7' roster's own formation
// with a run-leaning call — exactly makeGenome(OFFENSE_SPEC).)
export const OFFENSE_GENOME = {
  "meta": {
    "variant": "7",
    "note": "hand-written seed: roster formation, run-leaning call"
  },
  "values": {
    "pos:o-c:across": 0, "pos:o-c:down": -1,
    "pos:o-lg:across": -2.5, "pos:o-lg:down": -1,
    "pos:o-rg:across": 2.5, "pos:o-rg:down": -1,
    "pos:o-wr1:across": -15, "pos:o-wr1:down": -1,
    "pos:o-wr2:across": 15, "pos:o-wr2:down": -1,
    "pos:o-qb:across": 0, "pos:o-qb:down": -4,
    "pos:o-rb:across": 0, "pos:o-rb:down": -7,
    "call:bias": -2, "call:down": 0, "call:toGo": 1, "call:box": 1,
    "run:sideBias": 0.5, "run:read": 6, "run:lean": 0.5,
    "throw:go": 8, "throw:hold": 3, "qb:drop": 0.6,
    "tgt:sep": 1, "tgt:depth": 0.5, "tgt:dist": -0.3,
    "route:o-wr1:deg0": -20, "route:o-wr1:degLate": 0,
    "route:o-wr2:deg0": 20, "route:o-wr2:degLate": 0,
    "route:o-rb:deg0": 0, "route:o-rb:degLate": 30
  }
};
